
// User profile data
export const userProfile = {
  name: 'Alex Johnson',
  email: 'alex@example.com',
  role: 'student',
  streak: 7,
  goals: [
    'Master React and TypeScript',
    'Build a full-stack application',
    'Learn GraphQL'
  ]
};

// Roadmap data
export const roadmapData = [
  {
    id: 'road-1',
    title: 'Frontend Development Path',
    description: 'Learn the fundamentals of frontend web development with HTML, CSS, and JavaScript.',
    level: 'beginner' as const,
    progress: 75,
    resources: [
      {
        id: 'res-1-1',
        type: 'video' as const,
        title: 'HTML Fundamentals',
        duration: '45 min',
        completed: true,
        locked: false,
      },
      {
        id: 'res-1-2',
        type: 'article' as const,
        title: 'CSS Layout Techniques',
        duration: '20 min',
        completed: true,
        locked: false,
      },
      {
        id: 'res-1-3',
        type: 'tutorial' as const,
        title: 'JavaScript Basics',
        duration: '60 min',
        completed: false,
        locked: false,
      },
      {
        id: 'res-1-4',
        type: 'video' as const,
        title: 'DOM Manipulation',
        duration: '35 min',
        completed: false,
        locked: true,
      },
    ],
  },
  {
    id: 'road-2',
    title: 'React Development Path',
    description: 'Learn to build interactive user interfaces with React, hooks, and state management.',
    level: 'intermediate' as const,
    progress: 40,
    resources: [
      {
        id: 'res-2-1',
        type: 'video' as const,
        title: 'React Fundamentals',
        duration: '60 min',
        completed: true,
        locked: false,
      },
      {
        id: 'res-2-2',
        type: 'tutorial' as const,
        title: 'Working with Hooks',
        duration: '45 min',
        completed: false,
        locked: false,
      },
      {
        id: 'res-2-3',
        type: 'article' as const,
        title: 'State Management',
        duration: '30 min',
        completed: false,
        locked: true,
      },
    ],
  },
  {
    id: 'road-3',
    title: 'Full Stack Development',
    description: 'Master both frontend and backend to become a full stack developer.',
    level: 'advanced' as const,
    progress: 20,
    resources: [
      {
        id: 'res-3-1',
        type: 'tutorial' as const,
        title: 'Backend with Node.js',
        duration: '75 min',
        completed: true,
        locked: false,
      },
      {
        id: 'res-3-2',
        type: 'video' as const,
        title: 'Database Integration',
        duration: '60 min',
        completed: false,
        locked: false,
      },
      {
        id: 'res-3-3',
        type: 'article' as const,
        title: 'API Development',
        duration: '45 min',
        completed: false,
        locked: true,
      },
    ],
  },
];

// Learning resources data
export const resourcesData = [
  {
    id: 'res-1',
    title: 'Modern JavaScript for React Developers',
    description: 'Learn the essential JavaScript concepts needed for effective React development.',
    type: 'article' as const,
    duration: '25 min',
    level: 'beginner' as const,
    rating: 4.8,
    source: 'JavaScript Weekly',
    url: '#',
  },
  {
    id: 'res-2',
    title: 'React Hooks Explained',
    description: 'A comprehensive guide to understanding and using React Hooks in your applications.',
    type: 'video' as const,
    duration: '42 min',
    level: 'intermediate' as const,
    rating: 4.9,
    source: 'React Mastery',
    url: '#',
  },
  {
    id: 'res-3',
    title: 'Building a REST API with Node.js',
    description: 'Step-by-step tutorial for creating a RESTful API using Node.js and Express.',
    type: 'tutorial' as const,
    duration: '60 min',
    level: 'intermediate' as const,
    rating: 4.7,
    source: 'Node University',
    url: '#',
  },
  {
    id: 'res-4',
    title: 'CSS Grid and Flexbox Masterclass',
    description: 'Learn modern CSS layout techniques with Grid and Flexbox.',
    type: 'course' as const,
    duration: '3.5 hours',
    level: 'beginner' as const,
    rating: 4.6,
    source: 'CSS Tricks',
    url: '#',
  },
  {
    id: 'res-5',
    title: 'TypeScript for React Developers',
    description: 'Learn how to use TypeScript with React to create type-safe applications.',
    type: 'article' as const,
    duration: '30 min',
    level: 'intermediate' as const,
    rating: 4.5,
    source: 'TypeScript Weekly',
    url: '#',
  },
  {
    id: 'res-6',
    title: 'Advanced React Patterns',
    description: 'Dive into advanced React patterns and techniques used by professionals.',
    type: 'video' as const,
    duration: '55 min',
    level: 'advanced' as const,
    rating: 4.9,
    source: 'React Summit',
    url: '#',
  },
];
