
export const roadmapData = [
  {
    id: '1',
    title: 'Web Development Fundamentals',
    description: 'Learn the core concepts of modern web development including HTML, CSS and JavaScript.',
    level: 'beginner',
    progress: 75,
    resources: [
      {
        id: '101',
        type: 'video',
        title: 'Introduction to HTML',
        duration: '15 min',
        completed: true,
        locked: false,
      },
      {
        id: '102',
        type: 'article',
        title: 'CSS Basics & Styling',
        duration: '20 min',
        completed: true,
        locked: false,
      },
      {
        id: '103',
        type: 'tutorial',
        title: 'JavaScript Fundamentals',
        duration: '45 min',
        completed: false,
        locked: false,
      },
      {
        id: '104',
        type: 'video',
        title: 'Responsive Design Principles',
        duration: '25 min',
        completed: false,
        locked: true,
      },
    ],
  },
  {
    id: '2',
    title: 'React.js Framework',
    description: 'Master the popular React.js library for building interactive user interfaces.',
    level: 'intermediate',
    progress: 45,
    resources: [
      {
        id: '201',
        type: 'video',
        title: 'React Core Concepts',
        duration: '30 min',
        completed: true,
        locked: false,
      },
      {
        id: '202',
        type: 'tutorial',
        title: 'State Management in React',
        duration: '40 min',
        completed: true,
        locked: false,
      },
      {
        id: '203',
        type: 'article',
        title: 'React Hooks in Depth',
        duration: '25 min',
        completed: false,
        locked: false,
      },
      {
        id: '204',
        type: 'video',
        title: 'Building a Complete React App',
        duration: '60 min',
        completed: false,
        locked: true,
      },
    ],
  },
  {
    id: '3',
    title: 'TypeScript Essentials',
    description: 'Learn TypeScript to add static typing to your JavaScript applications.',
    level: 'intermediate',
    progress: 30,
    resources: [
      {
        id: '301',
        type: 'article',
        title: 'TypeScript vs JavaScript',
        duration: '15 min',
        completed: true,
        locked: false,
      },
      {
        id: '302',
        type: 'video',
        title: 'Basic Types & Interfaces',
        duration: '25 min',
        completed: false,
        locked: false,
      },
      {
        id: '303',
        type: 'tutorial',
        title: 'TypeScript with React',
        duration: '35 min',
        completed: false,
        locked: true,
      },
      {
        id: '304',
        type: 'article',
        title: 'Advanced TypeScript Features',
        duration: '30 min',
        completed: false,
        locked: true,
      },
    ],
  },
  {
    id: '4',
    title: 'Advanced CSS Techniques',
    description: 'Deep dive into modern CSS frameworks, animations, and layout techniques.',
    level: 'advanced',
    progress: 90,
    resources: [
      {
        id: '401',
        type: 'video',
        title: 'CSS Grid in Depth',
        duration: '30 min',
        completed: true,
        locked: false,
      },
      {
        id: '402',
        type: 'tutorial',
        title: 'CSS Animations & Transitions',
        duration: '45 min',
        completed: true,
        locked: false,
      },
      {
        id: '403',
        type: 'article',
        title: 'CSS Architecture Patterns',
        duration: '20 min',
        completed: true,
        locked: false,
      },
      {
        id: '404',
        type: 'video',
        title: 'Advanced Responsive Techniques',
        duration: '35 min',
        completed: true,
        locked: false,
      },
    ],
  },
];

export const resourcesData = [
  {
    id: '1',
    title: 'Introduction to Modern JavaScript Development',
    description: 'A comprehensive guide to the latest JavaScript features and best practices for modern web development.',
    type: 'article',
    duration: '25 min read',
    level: 'beginner',
    rating: 4,
    source: 'MDN Web Docs',
    url: '#',
  },
  {
    id: '2',
    title: 'Building Responsive Layouts with CSS Grid',
    description: 'Learn how to create flexible and responsive layouts using CSS Grid, the modern layout system for web applications.',
    type: 'video',
    duration: '32 min',
    level: 'intermediate',
    rating: 5,
    source: 'CSS Tricks',
    url: '#',
  },
  {
    id: '3',
    title: 'React Hooks: From Zero to Hero',
    description: 'Master React Hooks to manage state, side effects, and more in your functional components without class-based components.',
    type: 'tutorial',
    duration: '1.5 hours',
    level: 'intermediate',
    rating: 5,
    source: 'React Documentation',
    url: '#',
  },
  {
    id: '4',
    title: 'TypeScript for JavaScript Developers',
    description: 'A practical introduction to TypeScript for experienced JavaScript developers looking to enhance their code quality.',
    type: 'course',
    duration: '4 hours',
    level: 'intermediate',
    rating: 4,
    source: 'TypeScript Handbook',
    url: '#',
  },
  {
    id: '5',
    title: 'Advanced State Management in React with Redux',
    description: 'Dive deep into Redux architecture and learn how to manage complex state in large React applications efficiently.',
    type: 'tutorial',
    duration: '2 hours',
    level: 'advanced',
    rating: 4,
    source: 'Redux Documentation',
    url: '#',
  },
  {
    id: '6',
    title: 'RESTful API Design Best Practices',
    description: 'Learn how to design, build, and document RESTful APIs that are easy to use, maintain, and scale.',
    type: 'article',
    duration: '35 min read',
    level: 'intermediate',
    rating: 3,
    source: 'API Handbook',
    url: '#',
  },
  {
    id: '7',
    title: 'CSS Animations and Transitions for Modern Web Design',
    description: 'Create engaging user experiences with smooth animations and transitions using pure CSS techniques.',
    type: 'video',
    duration: '45 min',
    level: 'intermediate',
    rating: 5,
    source: 'Frontend Masters',
    url: '#',
  },
  {
    id: '8',
    title: 'Full-Stack Development with Node.js and Express',
    description: 'Build complete web applications by creating server-side applications with Node.js and Express framework.',
    type: 'course',
    duration: '6 hours',
    level: 'advanced',
    rating: 4,
    source: 'Node.js Documentation',
    url: '#',
  },
];

export const userProfile = {
  id: '12345',
  name: 'Alex Johnson',
  email: 'alex.johnson@example.com',
  avatarUrl: 'https://i.pravatar.cc/300',
  joinDate: '2023-07-15',
  learningStats: {
    completedTopics: 12,
    totalHoursLearning: 28,
    currentStreak: 5,
    longestStreak: 14,
    badges: 8,
  },
  interests: [
    'Web Development',
    'UI/UX Design',
    'JavaScript',
    'React',
    'TypeScript',
  ],
  goals: [
    'Master React and its ecosystem',
    'Learn TypeScript fundamentals',
    'Build a full-stack web application',
  ],
};
